# Generated by Django 3.0.7 on 2020-06-28 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_class', models.CharField(max_length=2)),
                ('student_section', models.CharField(max_length=1)),
                ('student_roll_no', models.CharField(max_length=5, unique=True)),
                ('marks_obtained_in_percent', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
